-- RUN THIS ENTIRE SCRIPT IN SUPABASE SQL EDITOR

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  document_date date not null,
  document_name text not null,
  school_year text,
  semester text,
  trusted_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.signatories (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(id) on delete cascade,
  signatory_name text not null,
  signed_at timestamptz null,
  received_by text null,
  received_at timestamptz null
);

alter table public.documents enable row level security;
alter table public.signatories enable row level security;

drop policy if exists documents_select_anon on public.documents;
create policy documents_select_anon on public.documents for select to anon using (true);

drop policy if exists documents_insert_anon on public.documents;
create policy documents_insert_anon on public.documents for insert to anon with check (true);

drop policy if exists documents_update_anon on public.documents;
create policy documents_update_anon on public.documents for update to anon using (true) with check (true);

drop policy if exists documents_delete_anon on public.documents;
create policy documents_delete_anon on public.documents for delete to anon using (true);

drop policy if exists signatories_select_anon on public.signatories;
create policy signatories_select_anon on public.signatories for select to anon using (true);

drop policy if exists signatories_insert_anon on public.signatories;
create policy signatories_insert_anon on public.signatories for insert to anon with check (true);

drop policy if exists signatories_update_anon on public.signatories;
create policy signatories_update_anon on public.signatories for update to anon using (true) with check (true);

drop policy if exists signatories_delete_anon on public.signatories;
create policy signatories_delete_anon on public.signatories for delete to anon using (true);
