-- Document Signature Monitoring Database
-- Supabase / PostgreSQL

create table if not exists documents (
    id bigint generated by default as identity primary key,
    document_date date not null,
    document_name text not null,
    school_year text,
    semester text,
    trusted_by text,
    created_at timestamptz default now()
);

create table if not exists signatories (
    id bigint generated by default as identity primary key,
    document_id bigint references documents(id) on delete cascade,
    signatory_name text not null,
    signed_at timestamptz,
    received_by text,
    received_at timestamptz
);

alter table documents enable row level security;
alter table signatories enable row level security;

drop policy if exists "Public can view documents" on documents;
create policy "Public can view documents" on documents
for select to anon using (true);

drop policy if exists "Public can insert documents" on documents;
create policy "Public can insert documents" on documents
for insert to anon with check (true);

drop policy if exists "Public can update documents" on documents;
create policy "Public can update documents" on documents
for update to anon using (true) with check (true);

drop policy if exists "Public can delete documents" on documents;
create policy "Public can delete documents" on documents
for delete to anon using (true);

drop policy if exists "Public can view signatories" on signatories;
create policy "Public can view signatories" on signatories
for select to anon using (true);

drop policy if exists "Public can insert signatories" on signatories;
create policy "Public can insert signatories" on signatories
for insert to anon with check (true);

drop policy if exists "Public can update signatories" on signatories;
create policy "Public can update signatories" on signatories
for update to anon using (true) with check (true);

drop policy if exists "Public can delete signatories" on signatories;
create policy "Public can delete signatories" on signatories
for delete to anon using (true);
